/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MemberLinks = {
  _type: "memberLinks";
  profile?: string;
  email?: string;
  scholar?: string;
  officeHours?: string;
};

export type PubLinks = {
  _type: "pubLinks";
  pdf?: string;
  doi?: string;
  slides?: string;
  video?: string;
};

export type SocialLinks = {
  _type: "socialLinks";
  twitter?: string;
  linkedin?: string;
  youtube?: string;
};

export type ResourceLink = {
  _type: "resourceLink";
  label?: string;
  url?: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type DisciplineReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "discipline";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  code?: string;
  description?: string;
  term?: string;
  discipline?: DisciplineReference;
  disciplineName?: string;
  link?: string;
  orderRank?: string;
};

export type ProgramContact = {
  _id: string;
  _type: "programContact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  discipline?: DisciplineReference;
  disciplineName?: string;
  lead?: string;
  email?: string;
  orderRank?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: BlockContent;
  defaultOpen?: boolean;
  orderRank?: string;
};

export type Milestone = {
  _id: string;
  _type: "milestone";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: string;
  description?: string;
  orderRank?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  office?: string;
  researchInterests?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: MemberLinks;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  status?: "upcoming" | "past";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  date?: string;
  dateLabel?: string;
  description?: string;
  tags?: Array<string>;
  resourceLinks?: Array<
    {
      _key: string;
    } & ResourceLink
  >;
  cta?: ResourceLink;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  year?: number;
  type?: "journal" | "conference" | "book" | "report";
  authors?: string;
  venue?: string;
  doi?: string;
  openAccess?: boolean;
  links?: PubLinks;
  tags?: Array<string>;
  featured?: boolean;
  abstract?: BlockContent;
};

export type ResearchArea = {
  _id: string;
  _type: "researchArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
  description?: BlockContent;
  link?: CtaLink;
  isFocusTile?: boolean;
  isHighlight?: boolean;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Student = {
  _id: string;
  _type: "student";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  linkedin?: string;
};

export type StudentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "student";
};

export type SiteStat = {
  _id: string;
  _type: "siteStat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: "labs" | "publications" | "students" | "partners";
  label?: string;
  value?: string;
  hasModal?: boolean;
  modalTitle?: string;
  modalContent?: BlockContent;
  hasSearch?: boolean;
  students?: Array<
    {
      _key: string;
    } & StudentReference
  >;
  orderRank?: string;
};

export type HeroSlide = {
  _id: string;
  _type: "heroSlide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imagePosition?: string;
  description?: string;
  ctaPrimary?: CtaLink;
  ctaSecondary?: CtaLink;
  orderRank?: string;
};

export type Discipline = {
  _id: string;
  _type: "discipline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
  };
  about?: {
    heading?: string;
    paragraphs?: Array<string>;
    disciplinesHeading?: string;
    disciplines?: Array<string>;
    studentPathwayHeading?: string;
    studentPathway?: string;
  };
  mission?: {
    heading?: string;
    text?: string;
    bullets?: Array<string>;
  };
  vision?: {
    heading?: string;
    text?: string;
    stats?: Array<{
      label?: string;
      value?: string;
      _key: string;
    }>;
  };
  whatWeDo?: {
    heading?: string;
    cards?: Array<{
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  footerTagline?: string;
  address?: string;
  phone?: string;
  officeHours?: string;
  primaryEmail?: string;
  socials?: SocialLinks;
  googleMapsEmbedUrl?: string;
  logos?: {
    sireLogo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    sireIcon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    msuLogo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    favicon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  footerExploreLinks?: Array<
    {
      _key: string;
    } & CtaLink
  >;
  footerResourceLinks?: Array<
    {
      _key: string;
    } & ResourceLink
  >;
  web3formsAccessKey?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MemberLinks
  | PubLinks
  | SocialLinks
  | ResourceLink
  | CtaLink
  | SanityImageAssetReference
  | BlockContent
  | DisciplineReference
  | Course
  | ProgramContact
  | Faq
  | Milestone
  | TeamMember
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | Publication
  | ResearchArea
  | Slug
  | Student
  | StudentReference
  | SiteStat
  | HeroSlide
  | Discipline
  | AboutPage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
